;;;; src/with-macros.lisp
;;;;
;;;; DEFINE-WITH-MACRO turns a CALL-WITH-X thunk-passing function into its
;;;; WITH-X scoping macro. Every HOST-KIT scope macro (WITH-TEMPORARY-FILE,
;;;; WITH-DIRECTORY-ENTRIES, WITH-FILE-LOCK, ...) is generated by it, so the
;;;; CPS shape and the "bound variables must be non-constant symbols"
;;;; diagnostic are written once instead of once per macro.
(in-package #:host-kit)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (defun %macro-variable-name-p (name)
    "Return true when NAME is a legal lexical-binding target for a macro."
    (and (symbolp name) (not (constantp name))))

  (defun %validate-bound-variables (bound-vars)
    "Signal an error naming the first non-symbol entry in BOUND-VARS."
    (dolist (var bound-vars)
      (unless (%macro-variable-name-p var)
        (error "Each bound variable must be a non-constant symbol: ~S" var)))
    bound-vars)

  (defun %split-forwarded-arguments (forwarded-args)
    "Split FORWARDED-ARGS into (VALUES POSITIONAL-ARGS KEYWORD-PLIST).
The keyword region begins at FORWARDED-ARGS' first keyword-symbol element;
every WITH-X positional argument (a pathname, a program, ...) is never itself
a bare keyword, so this split is unambiguous."
    (let ((split (position-if #'keywordp forwarded-args)))
      (if split
          (values (subseq forwarded-args 0 split) (subseq forwarded-args split))
          (values forwarded-args nil))))

  (defun %wrap-lazy-keyword-arguments (keyword-plist lazy-keys)
    "Return KEYWORD-PLIST with each value following a key in LAZY-KEYS wrapped
in a zero-argument thunk, deferring its evaluation past the WITH-X call site
so it can observe BODY's effects (e.g. :KEEP a flag BODY sets on success)."
    (loop for (key value) on keyword-plist by #'cddr
          collect key
          collect (if (member key lazy-keys) `(lambda () ,value) value))))

(defmacro define-with-macro (name (&rest bound-vars) call-with-function &key lazy-keys)
  "Define NAME as the CPS scoping macro over CALL-WITH-FUNCTION.
NAME's call form is (NAME (BOUND-VARS... . FORWARDED-ARGS) &body BODY).
Each BOUND-VARS symbol is validated as a non-constant symbol and lambda-bound
in CALL-WITH-FUNCTION's thunk. FORWARDED-ARGS -- positional arguments followed
by keyword arguments, exactly as CALL-WITH-FUNCTION itself accepts them after
its thunk -- is spliced verbatim, so an omitted keyword still defers to
CALL-WITH-FUNCTION's own default instead of a second, duplicated one. A
keyword named in LAZY-KEYS has its value deferred into a zero-argument thunk."
  (let ((forwarded-args (gensym "FORWARDED-ARGS"))
        (bound-var-values (gensym "BOUND-VAR-VALUES")))
    `(defmacro ,name ((,@bound-vars &rest ,forwarded-args) &body body)
       ,(format nil "Evaluate BODY with ~{~(~A~)~^, ~} scoped by ~(~A~)."
                bound-vars call-with-function)
       (%validate-bound-variables (list ,@bound-vars))
       (let ((,bound-var-values (list ,@bound-vars)))
         (multiple-value-bind (positional-args keyword-plist)
             (%split-forwarded-arguments ,forwarded-args)
           `(,',call-with-function
             (lambda ,,bound-var-values ,@body)
             ,@positional-args
             ,@(%wrap-lazy-keyword-arguments keyword-plist ',lazy-keys)))))))
